name: main
on:
  push:
    branches:
      - main
    # paths:
    #   - 'src/**'
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create a release
      pages: write
      id-token: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get latest tag
        id: latest
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: parse changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: get package version
        id: package
        uses: martinbeentjes/npm-get-version-action@main

      - name: verify versions match
        if: steps.changelog.outputs.version != steps.package.outputs.current-version
        run: |
          echo "version from package.json does not match that in CHANGELOG.md"
          echo "::set-job-status conclusion=failure::"

      - name: install nix
        uses: cachix/install-nix-action@v18

      - name: check flake
        run: nix flake check

      - name: build package
        run: |
          nix build --print-build-logs
          # https://github.com/actions/deploy-pages/issues/58
          cp -rL --no-preserve=mode,ownership ./result www

      - name: create release
        id: release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' && steps.changelog.outputs.version != steps.latest.outputs.tag
        with:
          # files: ./result (TODO: would need to archive)
          body: ${{ steps.changelog.outputs.description }}
          tag_name: ${{ steps.changelog.outputs.version }}

      - name: upload
        if: steps.release.outcome == 'success'
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./www

      - name: deploy
        if: steps.release.outcome == 'success'
        uses: actions/deploy-pages@v1
